const products = [
  // === RELOJES (Mayor precio primero) ===
  { name: "RELOJ", price: 18.00, stock: 1, barcode: "20204", category: "Relojes", description: "Reloj de acero inoxidable, resistente a salpicaduras de agua" },
  { name: "RELOJ", price: 18.00, stock: 1, barcode: "20203", category: "Relojes", description: "Reloj de acero inoxidable, resistente a salpicaduras de agua" },
  { name: "RELOJ", price: 15.00, stock: 1, barcode: "20202", category: "Relojes", description: "Reloj de acero inoxidable" },
  
  // === COLLARES ===
  { name: "COLLAR DE PERLAS", price: 12.00, stock: 1, barcode: "40102", category: "Collares", description: "Collar de perlas, acero inoxidable 304" },
  
  // === PULSERAS ($14.00 - $12.00) ===
  { name: "PULSERA DE CORAZONES", price: 14.00, stock: 1, barcode: "40206", category: "Pulseras", description: "Pulsera elegante de acero inoxidable 304 chapada en oro con circones" },
  { name: "PULSERA DE ZIRCONIA CORAZÓN", price: 12.00, stock: 1, barcode: "40207", category: "Pulseras", description: "Pulsera elegante de acero inoxidable 304 chapada en oro con zirconia" },
  { name: "PULSERA DE LUJO", price: 12.00, stock: 1, barcode: "030101", category: "Pulseras", description: "Brazalete de acero titanio elegante estilo clásico, resistente al agua y al deslustre" },
  { name: "PULSERA ESFERA ROMANOS", price: 12.00, stock: 1, barcode: "40106", category: "Pulseras", description: "Pulsera chapada en oro auténtico 18K, acero inoxidable 304, resistente al agua y deslustre" },
  { name: "CARTIER PLATEADA", price: 12.00, stock: 1, barcode: "40108", category: "Pulseras", description: "Brazalete chapado en oro 18K con circones" },
  { name: "ESTRELLA DE MAR CORAZÓN FRESA", price: 12.00, stock: 1, barcode: "40101", category: "Pulseras", description: "Pulsera de acero inoxidable 304 con dijes de estrella de mar, corazón y fresa" },
  { name: "PULSERA DE CORAZÓN ROSADO", price: 12.00, stock: 1, barcode: "40208", category: "Pulseras", description: "Pulsera minimalista de acero inoxidable 201 en forma de corazón" },
  
  // === PULSERAS ($10.00) ===
  { name: "BRAZALETE PARA MUJER", price: 10.00, stock: 1, barcode: "40209", category: "Pulseras", description: "Brazalete de acero inoxidable 304 bañado en oro, resistente al agua y deslustre con patrón de corazón" },
  { name: "PERLAS ORO BOLAS DOBLE CADENA", price: 10.00, stock: 1, barcode: "40107", category: "Pulseras", description: "Pulsera de corazón acero titanio básico, estilo simple, resistente al agua y deslustre" },
  { name: "PULSERA CEREZA FRESA", price: 10.00, stock: 1, barcode: "40201", category: "Pulseras", description: "Pulsera de acero inoxidable chapada en oro ajustable, estilo europeo y americano, diseño pulido de cereza y fresa" },
  
  // === ARITOS ===
  { name: "PENDIENTES ROJOS", price: 6.00, stock: 1, barcode: "40109", category: "Aritos", description: "Pendientes con aguja de plata S925, color vino rojo otoño" },
  { name: "PERLAS DE AGUA DULCE", price: 6.00, stock: 1, barcode: "40103", category: "Aritos", description: "Aritos de perlas de agua dulce con aguja de plata" },
  
  // === PULSERAS ($5.00) ===
  { name: "PULSERA VINTAGE PERLAS", price: 5.00, stock: 1, barcode: "40203", category: "Pulseras", description: "Pulsera vintage de perlas con piedra preciosa, estilo francés, sensación única de alta gama, material de aleación" },
  
  // === ARITOS (Menor precio) ===
  { name: "PENDIENTES DE COBRE", price: 4.00, stock: 1, barcode: "40204", category: "Aritos", description: "Pendientes de cobre con perla" },
  
  // ============================================
  // PRODUCTOS EXISTENTES (ya ordenados por categoría)
  // ============================================
  
  // CARTERAS (44 productos)
  { name: "BILLETERA", price: 10.00, stock: 0, barcode: "076", category: "Carteras" },
  { name: "BOLSO DE MANO", price: 10.00, stock: 1, barcode: "088", category: "Carteras" },
  { name: "CARTERA", price: 12.50, stock: 1, barcode: "03", category: "Carteras" },
  { name: "CARTERA", price: 12.00, stock: 1, barcode: "014", category: "Carteras" },
  { name: "CARTERA", price: 10.99, stock: 1, barcode: "033", category: "Carteras" },
  { name: "CARTERA", price: 16.50, stock: 0, barcode: "035", category: "Carteras" },
  { name: "CARTERA", price: 15.00, stock: 0, barcode: "071", category: "Carteras" },
  { name: "CARTERA", price: 10.00, stock: 1, barcode: "073", category: "Carteras" },
  { name: "CARTERA", price: 13.50, stock: 0, barcode: "00000", category: "Carteras" },
  { name: "CARTERA", price: 18.50, stock: 1, barcode: "086", category: "Carteras" },
  { name: "CARTERA", price: 18.50, stock: 1, barcode: "087", category: "Carteras" },
  { name: "CARTERA", price: 14.99, stock: 1, barcode: "089", category: "Carteras" },
  { name: "CARTERA", price: 14.99, stock: 1, barcode: "096", category: "Carteras" },
  { name: "CARTERA", price: 14.99, stock: 1, barcode: "097", category: "Carteras" },
  { name: "CARTERA", price: 24.00, stock: 1, barcode: "098", category: "Carteras" },
  { name: "CARTERA", price: 14.99, stock: 1, barcode: "099", category: "Carteras" },
  { name: "CARTERA", price: 14.99, stock: 0, barcode: "114", category: "Carteras" },
  { name: "CARTERA", price: 12.00, stock: 1, barcode: "127", category: "Carteras" },
  { name: "CARTERA", price: 13.99, stock: 1, barcode: "128", category: "Carteras" },
  { name: "CARTERA", price: 13.99, stock: 1, barcode: "129", category: "Carteras" },
  { name: "CARTERA", price: 15.00, stock: 0, barcode: "130", category: "Carteras" },
  { name: "CARTERA", price: 14.00, stock: 2, barcode: "132", category: "Carteras" },
  { name: "CARTERA", price: 14.99, stock: 1, barcode: "147", category: "Carteras" },
  { name: "CARTERA", price: 14.00, stock: 1, barcode: "148", category: "Carteras" },
  { name: "CARTERA", price: 15.99, stock: 1, barcode: "149", category: "Carteras" },
  { name: "CARTERA", price: 15.99, stock: 1, barcode: "150", category: "Carteras" },
  { name: "CARTERA", price: 13.50, stock: 0, barcode: "151", category: "Carteras" },
  { name: "CARTERA", price: 14.00, stock: 1, barcode: "152", category: "Carteras" },
  { name: "CARTERA", price: 14.00, stock: 0, barcode: "153", category: "Carteras" },
  { name: "CARTERA BEIG", price: 10.50, stock: 1, barcode: "068", category: "Carteras" },
  { name: "CARTERA BLANCA", price: 13.00, stock: 0, barcode: "022", category: "Carteras" },
  { name: "CARTERA BLANCA", price: 10.99, stock: 0, barcode: "049", category: "Carteras" },
  { name: "CARTERA BLANCA", price: 10.99, stock: 0, barcode: "058", category: "Carteras" },
  { name: "CARTERA BLANCA", price: 10.50, stock: 1, barcode: "063", category: "Carteras" },
  { name: "CARTERA BLANCA", price: 13.50, stock: 0, barcode: "075", category: "Carteras" },
  { name: "Cartera blanca", price: 10.99, stock: 0, barcode: "190", category: "Carteras" },
  { name: "CARTERA CAFE", price: 17.75, stock: 0, barcode: "899", category: "Carteras" },
  { name: "CARTERA CLASICA", price: 20.00, stock: 0, barcode: "051", category: "Carteras" },
  { name: "CARTERA CLASICA", price: 12.50, stock: 0, barcode: "061", category: "Carteras" },
  { name: "CARTERA MORADA", price: 10.99, stock: 0, barcode: "054", category: "Carteras" },
  { name: "CARTERA NEGRA", price: 10.99, stock: 1, barcode: "047", category: "Carteras" },
  { name: "CARTERA ROJA", price: 13.50, stock: 0, barcode: "074", category: "Carteras" },
  { name: "CARTERA ROSADA", price: 9.50, stock: 0, barcode: "023", category: "Carteras" },
  { name: "CARTERA VINO", price: 18.00, stock: 0, barcode: "053", category: "Carteras" },
  { name: "Carteras", price: 10.00, stock: 1, barcode: "181", category: "Carteras" },
  
  // ARITOS Y ARETES (49 productos) - CON DESCRIPCIÓN
  { name: "ARITOS", price: 3.50, stock: 1, barcode: "046", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 8.50, stock: 0, barcode: "179", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 7.00, stock: 1, barcode: "060", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOSS", price: 8.50, stock: 1, barcode: "174", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS DE CORAZON", price: 4.50, stock: 0, barcode: "056", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 6.00, stock: 0, barcode: "028393992", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 7.00, stock: 0, barcode: "06", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 5.00, stock: 0, barcode: "07", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 7.00, stock: 1, barcode: "09", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 7.00, stock: 0, barcode: "011", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 7.00, stock: 1, barcode: "013", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 3.50, stock: 0, barcode: "036", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 5.00, stock: 0, barcode: "079", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 4.00, stock: 0, barcode: "080", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 6.00, stock: 0, barcode: "081", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 6.50, stock: 0, barcode: "082", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 8.00, stock: 1, barcode: "085", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 3.50, stock: 0, barcode: "092", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 5.00, stock: 0, barcode: "100", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 5.50, stock: 1, barcode: "101", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 5.00, stock: 0, barcode: "102", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 8.00, stock: 1, barcode: "107", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 7.99, stock: 0, barcode: "108", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 6.99, stock: 1, barcode: "115", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 6.50, stock: 1, barcode: "116", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 7.50, stock: 1, barcode: "117", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 8.00, stock: 1, barcode: "118", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 6.00, stock: 0, barcode: "119", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 4.00, stock: 7, barcode: "124", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 5.50, stock: 0, barcode: "140", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 7.50, stock: 1, barcode: "156", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 8.99, stock: 1, barcode: "157", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 8.99, stock: 1, barcode: "158", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 7.00, stock: 3, barcode: "166", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 5.50, stock: 1, barcode: "168", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 6.50, stock: 0, barcode: "169", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 7.50, stock: 2, barcode: "170", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 6.50, stock: 1, barcode: "176", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 8.50, stock: 1, barcode: "178", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 8.50, stock: 1, barcode: "177", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 5.00, stock: 1, barcode: "19009", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS", price: 7.00, stock: 1, barcode: "190012", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "Aritos", price: 2.00, stock: 0, barcode: "1991919", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS DE ESTRELLA", price: 3.00, stock: 0, barcode: "019", category: "Aritos", description: "Aritos de acero inoxidable con laminado de oro de 14K resistentes a salpicaduras de agua, waterproof" },
  { name: "ARITOS DE ALEACION", price: 5.00, stock: 0, barcode: "02222", category: "Aritos", description: "Aritos DE ALTA GAMA" },
  { name: "AGUJA PLATA", price: 6.00, stock: 0, barcode: "02224", category: "Aritos", description: "AGUJA DE PLATA con BAÑADOS de oro de 14K RECOMENDACION NO MOJARLOS" },
  { name: "AGUJA PLATA", price: 6.00, stock: 0, barcode: "02226", category: "Aritos", description: "AGUJA DE PLATA con BAÑADOS de oro de 14K RECOMENDACION NO MOJARLOS" },
  { name: "AGUJA PLATA", price: 6.00, stock: 1, barcode: "02227", category: "Aritos", description: "AGUJA DE PLATA con BAÑADOS de oro de 14K RECOMENDACION NO MOJARLOS" },
  { name: "AGUJA PLATA", price: 6.00, stock: 1, barcode: "02228", category: "Aritos", description: "AGUJA DE PLATA con BAÑADOS de oro de 14K RECOMENDACION NO MOJARLOS" },
  
  // COLLARES (52 productos) - CON DESCRIPCIÓN
  { name: "Aritos", price: 5.50, stock: 0, barcode: "029", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLA DE PLAYA", price: 12.75, stock: 1, barcode: "066", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "Collar", price: 9.50, stock: 1, barcode: "10199191", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "Collar", price: 10.00, stock: 1, barcode: "17801", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 0, barcode: "024", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 1, barcode: "025", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 8.00, stock: 3, barcode: "028", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 15.00, stock: 1, barcode: "034", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 11.50, stock: 1, barcode: "039", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 10.00, stock: 0, barcode: "040", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 1, barcode: "070", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 11.50, stock: 1, barcode: "072", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 13.50, stock: 1, barcode: "077", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 0, barcode: "083", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 13.00, stock: 1, barcode: "084", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.50, stock: 1, barcode: "090", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 1, barcode: "091", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 1, barcode: "093", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 0, barcode: "094", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 0, barcode: "095", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 15.00, stock: 1, barcode: "104", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 11.00, stock: 0, barcode: "109", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 13.99, stock: 1, barcode: "110", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 14.99, stock: 1, barcode: "111", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 0, barcode: "113", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 1, barcode: "126", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 10.00, stock: 1, barcode: "133", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 2, barcode: "134", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 15.00, stock: 1, barcode: "135", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 15.00, stock: 1, barcode: "136", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 10.00, stock: 1, barcode: "139", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 10.00, stock: 1, barcode: "141", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.99, stock: 1, barcode: "145", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 10.00, stock: 1, barcode: "155", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 1, barcode: "163", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 1, barcode: "164", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 1, barcode: "165", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 0, barcode: "171", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 15.00, stock: 1, barcode: "172", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 1, barcode: "173", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 3, barcode: "175", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 10.00, stock: 1, barcode: "183", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 10.00, stock: 1, barcode: "184", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 10.00, stock: 1, barcode: "1200", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 12.00, stock: 1, barcode: "01116", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 10.00, stock: 1, barcode: "01127", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR", price: 10.00, stock: 0, barcode: "01129", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR CLASICO", price: 10.00, stock: 2, barcode: "020", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR DE CORAZON NEGRO", price: 10.00, stock: 1, barcode: "062", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR DE CRUZ REDONDO", price: 12.00, stock: 1, barcode: "016", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR DE FLOR", price: 10.50, stock: 1, barcode: "055", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR DE FLOR", price: 11.50, stock: 1, barcode: "065", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR DE PERLAS", price: 13.50, stock: 0, barcode: "048", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "collar de sol", price: 11.00, stock: 0, barcode: "89009", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR DOBLE", price: 15.00, stock: 0, barcode: "010", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR DOBLE", price: 15.00, stock: 1, barcode: "027", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "COLLAR DOBLE DE CORAZON", price: 14.00, stock: 0, barcode: "067", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "Collar mariposa", price: 10.00, stock: 0, barcode: "200", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "SET", price: 18.50, stock: 1, barcode: "142", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  { name: "SET DE COLLAR", price: 13.50, stock: 1, barcode: "078", category: "Collares", description: "Collares de acero inoxidable con laminado en oro de 18K resistentes a salpicaduras waterproof" },
  
  // LENTES (2 productos)
  { name: "LENTES", price: 7.50, stock: 1, barcode: "015", category: "Lentes de sol" },
  { name: "LENTES NEGROS", price: 5.75, stock: 1, barcode: "037", category: "Lentes de sol" },
  
  // PULSERAS (32 productos existentes + nuevos arriba)
  { name: "BRACELET", price: 7.00, stock: 0, barcode: "041", category: "Pulseras" },
  { name: "BRASALET", price: 10.00, stock: 0, barcode: "038", category: "Pulseras" },
  { name: "PULSERA", price: 5.00, stock: 1, barcode: "042", category: "Pulseras" },
  { name: "PULSERA", price: 7.00, stock: 2, barcode: "043", category: "Pulseras" },
  { name: "PULSERA", price: 10.00, stock: 1, barcode: "044", category: "Pulseras" },
  { name: "PULSERA", price: 6.00, stock: 0, barcode: "064", category: "Pulseras" },
  { name: "PULSERA", price: 12.00, stock: 0, barcode: "103", category: "Pulseras" },
  { name: "PULSERA", price: 12.99, stock: 1, barcode: "105", category: "Pulseras" },
  { name: "PULSERA", price: 10.00, stock: 0, barcode: "106", category: "Pulseras" },
  { name: "PULSERA", price: 10.00, stock: 0, barcode: "112", category: "Pulseras" },
  { name: "PULSERA", price: 12.00, stock: 1, barcode: "146", category: "Pulseras" },
  { name: "PULSERA", price: 13.00, stock: 3, barcode: "159", category: "Pulseras" },
  { name: "PULSERA", price: 10.00, stock: 0, barcode: "160", category: "Pulseras" },
  { name: "PULSERA", price: 9.00, stock: 0, barcode: "161", category: "Pulseras" },
  { name: "PULSERA", price: 12.00, stock: 0, barcode: "167", category: "Pulseras" },
  { name: "PULSERA", price: 10.00, stock: 0, barcode: "198", category: "Pulseras" },
  { name: "PULSERA", price: 8.00, stock: 1, barcode: "9789", category: "Pulseras" },
  { name: "PULSERA", price: 7.00, stock: 1, barcode: "8967", category: "Pulseras" },
  { name: "PULSERA", price: 5.50, stock: 0, barcode: "1250", category: "Pulseras" },
  { name: "PULSERA", price: 10.00, stock: 2, barcode: "01126", category: "Pulseras" },
  { name: "PULSERA", price: 10.50, stock: 1, barcode: "02221", category: "Pulseras" },
  { name: "PULSERA", price: 10.00, stock: 1, barcode: "02223", category: "Pulseras" },
  { name: "PULSERA", price: 12.00, stock: 1, barcode: "03331", category: "Pulseras" },
  { name: "PULSERA", price: 12.00, stock: 1, barcode: "03332", category: "Pulseras" },
  { name: "PULSERA", price: 10.00, stock: 0, barcode: "2001", category: "Pulseras" },
  { name: "PULSERA AJUSTABLE", price: 10.00, stock: 0, barcode: "018", category: "Pulseras" },
  { name: "PULSERA BASICA", price: 6.00, stock: 1, barcode: "030", category: "Pulseras" },
  { name: "PULSERA cartier", price: 10.00, stock: 0, barcode: "032", category: "Pulseras" },
  { name: "PULSERA CARTIER", price: 11.00, stock: 0, barcode: "031", category: "Pulseras" },
  { name: "PULSERA DE TREBOL", price: 12.00, stock: 2, barcode: "01118", category: "Pulseras" },
  { name: "VAN CLEEF", price: 12.00, stock: 0, barcode: "050", category: "Pulseras" },
  
  // RELOJES (30 productos existentes + nuevos arriba)
  { name: "RELOJ", price: 15.00, stock: 1, barcode: "01111", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 20.00, stock: 0, barcode: "01125", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 16.00, stock: 1, barcode: "03333", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 25.00, stock: 1, barcode: "03334", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 16.00, stock: 1, barcode: "03335", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 20.00, stock: 1, barcode: "03336", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 15.00, stock: 1, barcode: "03337", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 20.00, stock: 0, barcode: "03338", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 20.00, stock: 1, barcode: "03339", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 15.00, stock: 0, barcode: "033340", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 15.00, stock: 1, barcode: "033341", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 15.00, stock: 1, barcode: "033342", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 15.00, stock: 1, barcode: "033343", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 20.00, stock: 1, barcode: "033344", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 15.00, stock: 1, barcode: "033345", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 15.00, stock: 1, barcode: "033346", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 25.00, stock: 1, barcode: "033347", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 30.00, stock: 0, barcode: "033348", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 20.00, stock: 1, barcode: "033349", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ", price: 18.00, stock: 2, barcode: "033350", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ BLANCO", price: 15.00, stock: 1, barcode: "011144", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ DE ACERO INOXIDABLE", price: 15.00, stock: 0, barcode: "01117", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ DE ACERO INOXIDABLE", price: 15.00, stock: 0, barcode: "01123", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ DORADO WATERPROOF", price: 20.00, stock: 0, barcode: "01122", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ NEGRO", price: 15.00, stock: 1, barcode: "01113", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ OLD MONEY", price: 15.00, stock: 0, barcode: "01124", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ ROJO", price: 15.00, stock: 1, barcode: "01119", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "RELOJ ROJO", price: 15.00, stock: 0, barcode: "01121", category: "Relojes", description: "Relojes de acero inoxidable" },
  { name: "SEET DE RELOJ Y PULSERA", price: 14.00, stock: 0, barcode: "01115", category: "Relojes", description: "Reloj de acero fino" },
  { name: "RELOJ SET", price: 40.00, stock: 1, barcode: "01112", category: "Relojes", description: "Relojes de acero inoxidable" },
  
  // ANILLOS (9 productos)
  { name: "ANILLO", price: 10.00, stock: 1, barcode: "02", category: "Anillos" },
  { name: "ANILLO", price: 10.00, stock: 1, barcode: "04", category: "Anillos" },
  { name: "ANILLO", price: 10.00, stock: 1, barcode: "08", category: "Anillos" },
  { name: "ANILLO", price: 10.00, stock: 1, barcode: "017", category: "Anillos" },
  { name: "ANILLO", price: 10.00, stock: 1, barcode: "021", category: "Anillos" },
  { name: "ANILLO", price: 10.00, stock: 1, barcode: "045", category: "Anillos" },
  { name: "ANILLO", price: 10.00, stock: 1, barcode: "057", category: "Anillos" },
  { name: "ANILO", price: 10.00, stock: 1, barcode: "059", category: "Anillos" },
  
  // OTROS (3 productos)
  { name: "ACCESORIOS", price: 0.25, stock: 20, barcode: "137", category: "Accesorios para el cabello" },
  { name: "CEREZA", price: 5.25, stock: 3, barcode: "122", category: "Otros" },
  { name: "TARJETAS NAVIDEÑAS", price: 0.00, stock: 121, barcode: "154", category: "Otros" }
];
